### ISSUE TITLE
Update dependencies to newest version

### ISSUE THREAD

**Issue by mb-emag** [boschglobal/doxysphinx#100]
Right now we still use Sphinx 4.5 - mainly because the theme we're using (sphinx-books) wasn't compatible with newer sphinx releases last time we checked (been some time)...

Meanwhile sphinx-books got a big update so we can update, however on a quick first look this created some issues:
- styling is broken
   - this needs some css fixes.
   - there is now a dark mode which is completely unsupported by us right now (need to check if this could be combined with doxygen awesome dark mode)
   - btw. we should also update doxygen awesome
   - as we're also supporting rtd-theme we should also check it's behavior...
   
All this might be a breaking change for existing doxysphinx users, therefore we should consider doing a major version bump on this one.

**Comment by Maetveis** [comment]
> - there is now a dark mode which is completely unsupported by us right now (need to check if this could be combined with doxygen awesome dark mode)

I can chime in here: it can be done. I have done this for the upcoming ROCm documentation, by slightly editing doxygen-awesome. You can see it here: https://advanced-micro-devices-rocm-docs-core.readthedocs-hosted.com/en/latest/demo/doxygen/html/example_8hpp.html. I would gladly help to clean this up a little and upstream it.

**Comment by mb-emag** [comment]
Hi @Maetveis,

that looks totally awesome sir! We would really like to have this! 😀

**Comment by twodrops** [comment]
The above hosting seems to have moved. I found it here again
https://rocm.docs.amd.com/projects/rocAL/en/latest/doxygen/html/group__group__rocal.html
(not the demo above however, but doxysphinx usage)

**Comment by twodrops** [comment]
@Maetveis Do you still have the time to contribute this upstream? It would be really great! See related PR [here](https://github.com/boschglobal/doxysphinx/pull/130).

**Comment by Maetveis** [comment]
> @Maetveis Do you still have the time to contribute this upstream? It would be really great! See related PR [here](https://github.com/boschglobal/doxysphinx/pull/130).

I will probably have time next weekend, until that I will summarize what I did on the PR, if someone wants to do it.
