### ISSUE TITLE
make doxysphinx a generic sphinx HTML integration tool

### ISSUE THREAD

**Issue by mb-emag** [boschglobal/doxysphinx#15]
At present doxysphinx only supports integrating doxgen documentation with sphinx. However there are many other tools which generate some kind of html documentation but aren't integrated into sphinx very easily otherwise.

We could make doxysphinx a generic html integrator, perhaps though something like a processor-layer where each processor implements rst generation for a specific kind of input html format (.e.g. "doxygen", "ea", "word" etc.).

**Comment by twodrops** [comment]
Is not of high prio for now. So let us close it and reopen if needed.
