### ISSUE TITLE
Path validation throws warnings although Doxysphinx generates everything correctly

### ISSUE THREAD

**Issue by twodrops** [boschglobal/doxysphinx#65]
The path validation feature throws two warnings although the paths are correct and everything is getting generated correctly with doxysphinx

>warning: Not all optional doxygen settings are set correctly:
warning: Hint: Wrong value docs/source/design/doxygen-awesome.css for HTML_EXTRA_STYLESHEET, YOUR_DOXYGEN_AWESOME_PATH/doxygen-awesome.css is recommended.
warning: Hint: Wrong value docs/_doxygen/tagfile.xml for GENERATE_TAGFILE, docs/_doxygen/html/tagfile.xml is recommended.

The paths in Doxyfile are as follows:

>OUTPUT_DIRECTORY       = docs/_doxygen/
>HTML_EXTRA_STYLESHEET  = docs/source/design/doxygen-awesome.css
>GENERATE_TAGFILE       = docs/_doxygen/tagfile.xml

All paths are relative to the root and doxygen generates the output correctly in the output folder. 

Hint:
Doxysphinx is running inside a Linux Docker Container.

**Comment by mb-emag** [comment]
Fixed.
