### ISSUE TITLE
Relax GENERATE_XML validation

### ISSUE THREAD

**Issue by twodrops** [boschglobal/doxysphinx#66]
> GENERATE_XML = YES

is useful when Doxysphinx and Breathe are used together. 

Breathe is still useful to include doxygenclass, doxygenfunction etc. inline into rST files (not the complete doxygen generation)

Shall we relax the validation on this attribute?

**Comment by mb-emag** [comment]
Yes we remove it - it was only there in the first place to prevent users doing both because of the increased doxygen generation times.

**Comment by mb-emag** [comment]
My apologies!
We removed the validation on GENERATE_XML in f584b912b67caf59baa6d5c5ca8621664d58fb49. It's active since release 2.3.7.
