### ISSUE TITLE
Duplicate elements in Navbar

### ISSUE THREAD

**Issue by twodrops** [boschglobal/doxysphinx#69]
When doxysphinx results are included into the RTD Theme navbar, it creates duplicate entries

![image](https://user-images.githubusercontent.com/103930/189634639-9efcd3b0-fd77-4e73-8a7a-a8b07ab611e2.png)
![image](https://user-images.githubusercontent.com/103930/189634669-a0406adb-742d-4f5e-9dd2-63e333d0b837.png)

Doxysphinx: 2.0.8
Python: 3.8.10
Sphinx: 4.5.0
Doxygen: 1.8.17
RTD Theme: 1.0.0

**Comment by sky-dream** [comment]
i am facing the same problem on the sphinx_book_theme , hope this issue can be fixed ASAP.
doxysphinx, version 2.1.9
doxygen version 1.9.4
Sphinx: 4.5.0
