### ISSUE TITLE
Support incremental behaviour for Doxysphinx

### ISSUE THREAD

**Issue by twodrops** [boschglobal/doxysphinx#81]
Doxypsphinx currently generates rSTs for Doxygen HTMLs always. This affects the incremental build of Sphinx. It would be nice to get incremental behavior into Doxyphinx in two steps.

- If there is no change in Doxygen HTML output compared to the previous run, Doxysphinx does not run at all
- If only certain Doxygen HTMLs are changed, only those rSTs are newly regenerated and unchanged rSTs from previous run is reused.

There are certain inconsistencies that could happen with this.

- Sphinx does not behavior correctly when page labels are changed and they are referenced from other files
- Sphinx-Needs bi-directional links are not consistent if the references are between needs in two Doxygen fikes.

These are however Sphinx/Sphinx-Needs problems to be solved and not in Doxysphinx.

**Comment by twodrops** [comment]
> Using hash of HTML files to check if the file is changed and including the HTML file for doxysphinx build if hash is changed.
> 
> Note: Sometimes the doxygen build changes the HTML formatting which leads to building non necessary rst file generations. As shown in figure position for <\div> is changed.
> 
> ![image](https://user-images.githubusercontent.com/14127049/212697674-15635f11-33d5-4ad3-a35f-82f59c4935a6.png)

That's really strange. No tool should behave in that way. It should be a deterministic behaviour by all generators.
I guess we should setup a test data and create a bug report for Doxygen. 

To overcome this,, we could do a HTML whitespace compression and send it for hash generation always. This means that all whitespace within HTML CDATA will be retained, but outside it (that means, space and new line between tags) will be compressed. 
 

```
<div>
<p>This is a para with long space               in between</p>
    </div>
```
 
will be formatted in buffer as
 
`<div><p>This is a para with long space               in between</p></div>
 `
If this works, we can leave this as default and make it configurable in Doxysphinx, if needed.
 
`doxysphinx_incremental_check_aggresive=true` or something like this.

What do you think?

**Comment by aniketsalve22** [comment]
> > Using hash of HTML files to check if the file is changed and including the HTML file for doxysphinx build if hash is changed.
> > Note: Sometimes the doxygen build changes the HTML formatting which leads to building non necessary rst file generations. As shown in figure position for <\div> is changed.
> > ![image](https://user-images.githubusercontent.com/14127049/212697674-15635f11-33d5-4ad3-a35f-82f59c4935a6.png)
> 
> That's really strange. No tool should behave in that way. It should be a deterministic behaviour by all generators. I guess we should setup a test data and create a bug report for Doxygen.
> 
> To overcome this, we could do a HTML whitespace compression and send it for hash generation always. This means that all whitespace within HTML CDATA will be retained, but outside it (that means, space and new line between tags) will be compressed.   
> 
> ```
> <div>
> <p>This is a para with long space               in between</p>
>     </div>
> ```
> 
> will be formatted in buffer as   `<div><p>This is a para with long space               in between</p></div>  ` If this works, we can leave this as default and make it configurable in Doxysphinx, if needed.   `doxysphinx_incremental_check_aggresive=true` or something like this.
> 
> What do you think?

I think it should work. Tested it multiple times as well. So I think we can always create hash after removing the empty spaces without adding extra flags. Because if the file contents are same then doxysphinx should anyways ignore the file.
