### ISSUE TITLE
Project specific ALIASES definitions are not accepted in v3.0.0

### ISSUE THREAD

**Issue by takumiyake** [boschglobal/doxysphinx#88]
**Describe the bug**
When I used the previously working ALIASES Doxygen definition in the configuration file, the new Doxysphinx output an error that the mandatory configuration was not given. The code was checking the whole set of the dictionary (the key and the item), so it does not accept any project-specific new ALIASES definition. 

**To Reproduce**
1. Add a new ALIASES definition in the Doxygen configuration file in addition to \rst and \endrst definition
2. Run the Doxyshpinx to output the result

Example:
```
ALIASES  = "rst=\verbatim embed:rst:leading-asterisk" \
            endrst=\endverbatim  # This allows you to use rst blocks inside Doxygen comments with @rst and @endrst
ALIASES += decision="\xrefitem DECISION \"Decision\" \"Decision List\""
```

**Expected behavior**
No error will happen during the document generation.

**Screenshots**
This is a snippet for the issue-fix example.
```
   def _validate_doxygen_recommended_settings(self, settings: ConfigDict) -> bool:
        imported_settings = settings
        target_settings = self.mandatory_settings
        validation_successful = True
        # Original code
        # if all(item in imported_settings.items() for item in target_settings.items()):
        #     return validation_successful

        # Updated code
        if all(((target_settings[key] in imported_settings[key]
                 for key in target_settings.keys() if key != 'ALIASES'),
               set(target_settings['ALIASES']).issubset(imported_settings['ALIASES']))):
            return validation_successful

```

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Google Chrome
 - Version Doxyshpinx v3.0.0

**Comment by mb-emag** [comment]
My apologies!
This was fixed in December 2022 in the commit 81546a7f7243fba4b8cfa9fbc5406663fbe8b489 (release 3.1.0).
I missed to specify the "closes" command in the commit message.
